### ISSUE TITLE
Mock Server not starting in Windows

### ISSUE THREAD

**Issue by QAInsights** [up9inc/mockintosh#69]
I have installed Mockintosh as a Python package in Pycharm in Windows 10 Pro. After configuring the new service, the terminal output shows that Mock server is ready. But when I launch the localhost, it is not showing any response.

OS: Windows 10 Pro
Python version: 3.9

**service.yaml**
```
services:
  - name: capi
    port: 9001
    hostname: localhost
    endpoints:
      - path: /
        method: GET
        response: 'Hello World'
```

**Terminal Output**
```
[2021-03-11 22:13:42,024 root DEBUG] Configuration text: services:
  - name: capi
    port: 9001
    hostname: localhost
    endpoints:
      - path: /
        method: GET
        response: 'Hello World'
[2021-03-11 22:13:42,025 root INFO] Configuration file is a valid YAML file.
[2021-03-11 22:13:42,028 root INFO] Configuration file is valid according to the JSON schema.
[2021-03-11 22:13:42,029 root DEBUG] Templating engine (config) is: Handlebars
[2021-03-11 22:13:42,033 root INFO] Mock server is ready!
[2021-03-11 22:13:42,034 asyncio DEBUG] Using proactor: IocpProactor
```

**Comment by undera** [comment]
What does it mean `launch the localhost`? How exactly do you try to access the mock?

**Comment by undera** [comment]
Also, which version does Mockintosh report as first line of logging?

**Comment by QAInsights** [comment]
I opened the localhost:9001 in the browser which threw 404. I used --verbose log level.

**Comment by undera** [comment]
Recent versions of Mockintosh would print you a line like this:
```[2021-03-12 17:18:08,921 root INFO] Mockintosh v0.7 is starting...
```
Do you have that line?

**Comment by QAInsights** [comment]
No @undera . I tested it in my Raspberry Pi, Mockintosh is launching fine. But failed in Windows.

**Comment by undera** [comment]
Probably, Windows installation has took old version. I have tested on Windows - works good for me.
Try upgrading it, making sure the version is 0.7

**Comment by QAInsights** [comment]
@undera I am using 0.7 version. Also the default service is not starting. Here is the log.

```
(venv) C:\Users\Navee\PycharmProjects\MockintoshTest>mockintosh
[2021-03-12 10:21:40,561 root INFO] Mockintosh v0.7 is starting...
[2021-03-12 10:21:40,567 root INFO] Configuration file is valid according to the JSON schema.
[2021-03-12 10:21:40,574 root ERROR] Mock server loading error:
Traceback (most recent call last):
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\__init__.py", line 207, in run
    http_server = HttpServer(
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\servers.py", line 88, in __init__
    self.load()
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\servers.py", line 161, in load
    server.listen(service['port'], address=self.address)
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError

(venv) C:\Users\Navee\PycharmProjects\MockintoshTest>mockintosh app.yaml
[2021-03-12 10:22:01,761 root INFO] Mockintosh v0.7 is starting...
[2021-03-12 10:22:01,762 root INFO] Reading configuration file from path: app.yaml
[2021-03-12 10:22:01,764 root INFO] Configuration file is a valid YAML file.
[2021-03-12 10:22:01,767 root INFO] Configuration file is valid according to the JSON schema.
[2021-03-12 10:22:01,775 root ERROR] Mock server loading error:
Traceback (most recent call last):
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\__init__.py", line 207, in run
    http_server = HttpServer(
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\servers.py", line 88, in __init__
    self.load()
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\servers.py", line 192, in load
    server.listen(services[0]['port'], address=self.address)
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError

(venv) C:\Users\Navee\PycharmProjects\MockintoshTest>mockintosh app.yaml 'capi'
[2021-03-12 10:22:08,520 root INFO] Mockintosh v0.7 is starting...
[2021-03-12 10:22:08,520 root INFO] Reading configuration file from path: app.yaml
[2021-03-12 10:22:08,523 root INFO] Configuration file is a valid YAML file.
[2021-03-12 10:22:08,526 root INFO] Configuration file is valid according to the JSON schema.
[2021-03-12 10:22:08,530 root INFO] Mock server is ready!
Traceback (most recent call last):
  File "C:\Users\Navee\PycharmProjects\MockintoshTest\venv\Scripts\mockintosh-script.py", line 33, in <module>
    sys.exit(load_entry_point('mockintosh==0.7', 'console_scripts', 'mockintosh')())
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\__init__.py", line 303, in initiate
    run(source, debug=debug_mode, interceptors=interceptors, address=address, services_list=services_list)
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\__init__.py", line 219, in run
    http_server.run()
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\servers.py", line 247, in run
    self.impl.serve()
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\mockintosh\servers.py", line 66, in serve
    tornado.ioloop.IOLoop.current().start()
  File "c:\users\navee\pycharmprojects\mockintoshtest\venv\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 783, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
```

**Comment by undera** [comment]
Thanks for detailed report, we'll work on fixing that

**Comment by undera** [comment]
Can you try upgrading your Tornado library? I found known issue https://github.com/tornadoweb/tornado/issues/2608
Upgrading is like `pip install -U tornado`

**Comment by QAInsights** [comment]
Now it is working @undera :) 

```
(venv) C:\Users\Navee\PycharmProjects\MockintoshTest>mockintosh app.yaml
[2021-03-12 10:46:10,960 root INFO] Mockintosh v0.7 is starting...
[2021-03-12 10:46:10,960 root INFO] Reading configuration file from path: app.yaml
[2021-03-12 10:46:10,960 root INFO] Configuration file is a valid YAML file.
[2021-03-12 10:46:10,960 root INFO] Configuration file is valid according to the JSON schema.
[2021-03-12 10:46:10,976 root INFO] Serving at http://localhost:9001 the mock for 'capi'
[2021-03-12 10:46:10,976 root INFO] Mock server is ready!
[2021-03-12 10:46:27,437 tornado.access INFO] 200 GET / (127.0.0.1) 0.00ms
[2021-03-12 10:46:29,168 tornado.access WARNING] 404 GET /favicon.ico (127.0.0.1) 8.09ms
```

**Comment by undera** [comment]
Thanks for reporting the issue! We'll incorporate the fix into next version of Mockintosh.

**Comment by QAInsights** [comment]
Thanks. Closing this issue.
